### PR TITLE
Apply example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Not working*

## Solution
- *[Apply example_ynh](https://github.com/YunoHost-Apps/icecoder_ynh/commit/a55b130bd1f13e94a0e5ca37bc6e678594a27222)*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"* (You can only do this with an opened Pull Request)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by Stilic** [comment]
Sorry but I stopped maintaining my YunoHost packages, because I don't have time for that and chosen also to manage myself my server.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> Sorry but I stopped maintaining my YunoHost packages, because I don't have time for that and chosen also to manage myself my server.

No problems, as the app seems cool, I'm trying to make it work

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
